name: Echo datetime
on:
  workflow_dispatch: null
  schedule:
    - cron: "0 0 * * *"  # At 00:00 am every day on everyday
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y-%m-%dT%H:%M:%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW 
